### ISSUE TITLE
Unable to make it work with NetBeans 12.0

### ISSUE THREAD

**Issue by LaraSQP** [anchialas/CoolEditorActions#1]
It appears to install properly but it is neither displayed nor among the 'installed' plugins after a restart.

Any thoughts, workaround, or alternative plugin?

And, btw, thank you very, very much for developing the plugin and making it available for free. I've used it for years (with previous versions of NetBeans).

**Comment by anchialas** [comment]
Thank you for opening the first issue!

Please try again, I have just uploaded the new version, which is compatible with NetBeans 12.

**Comment by LaraSQP** [comment]
Much appreciated.
